import "./globals.css";
import { Inter } from "next/font/google";

// components
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  author: "Daniel B.OUATTARA",
  email: "daniel.ouattara[AT]gmx[.]com",
};

export default function RootLayout(props) {
  console.log("props =", props);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        {props.children}
      </body>
    </html>
  );
}
